article/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "article"

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('add_article/', views.add_article, name='add_article'),
    path('<int:id>/',views.detail, name='detail'),
    path('update/<int:id>/', views.update_article, name='update'),
    path('delete/<int:id>/', views.delete_article, name='delete'),
    path('articles/', views.articles, name='articles'),
    path('comment/<int:id>/', views.add_comment, name='comment'),

]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from article import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name="index"),
    path('about/', views.about, name="about"),
    path('article/', include('article.urls')),
    path('user/', include('user.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "user"

urlpatterns = [
     path('register/', views.register_user, name = 'register'),
     path('login/', views.login_user, name = 'login'),
     path('logout/', views.logout_user, name = 'logout'),
 ]
 

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.
class Article(models.Model):
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE,verbose_name="Author")
    title = models.CharField(max_length=50, verbose_name="Title")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Published date")
    article_image = models.FileField(blank=True, null=True, verbose_name="Add image to article")
    class Meta:
        ordering = ['-created_date']
    def __str__(self):
        return self.title
    
class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE,verbose_name="Article", related_name="comments")
    comment_author = models.CharField(max_length=50, verbose_name="Comment Author")
    comment_content = models.TextField(max_length=250, verbose_name="Content")
    comment_date = models.DateTimeField(auto_now_add=True, verbose_name="Published date")
    
    class Meta:
        ordering = ['-comment_date']
    def __str__(self):
        return self.comment_content

user/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content','article_image']
        

user/forms.py
from django import forms

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=50, label='Username')
    password = forms.CharField(max_length=20, label='Password', widget=forms.PasswordInput)
    confirm = forms.CharField(max_length=20, label='Confirm Password', widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        confirm = self.cleaned_data.get('confirm')

        if password and confirm and password != confirm:
            raise forms.ValidationError('Passwords are not same')

        values = {
            'username': username,
            'password': password,
        }

        return values

class LoginForm(forms.Form):
    username = forms.CharField(max_length=50, label='Username')
    password = forms.CharField(max_length=20, label='Password', widget=forms.PasswordInput)

article/views.py
from django.shortcuts import render,reverse,redirect,get_object_or_404
from .forms import ArticleForm
from .models import Article,Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    return render(request,'index.html')

def about(request):
    return render(request, 'about.html')

@login_required(login_url='user:login')
def dashboard(request):
    articles = Article.objects.filter(author=request.user)
    context = {
        'articles':articles,
    }
    return render(request, 'dashboard.html',context)

@login_required(login_url='user:login')
def add_article(request):
    form = ArticleForm(request.POST or None,request.FILES or None)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request, 'Your article was created successfully!')
        return redirect('article:dashboard') 
    context = {
        'form':form,
    }
    return render(request, 'add_article.html',context)

def detail(request, id):
    # article = Article.objects.filter(id=id).first()
    article = get_object_or_404(Article, id=id)
    comments = article.comments.all()
    context = {
        'article':article,
        'comments':comments,
    }
    return render(request, 'detail.html',context)

@login_required(login_url='user:login')
def update_article(request, id):
    article = get_object_or_404(Article,id=id)
    form = ArticleForm(request.POST or None, request.FILES or None, instance=article)

    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request, 'Your article was created successfully!')
        return redirect('article:dashboard') 
    context = {
        'form':form,
    }
    return render(request, 'update.html',context)

@login_required(login_url='user:login')
def delete_article(request,id):
    article = get_object_or_404(Article,id=id)
    article.delete()
    messages.success(request, "Article deleted successfully")
    return redirect('article:dashboard')

def articles(request):
    keyword = request.GET.get('keyword')

    articles = Article.objects.all()

    if keyword:
        articles = Article.objects.filter(title__contains = keyword)

    context = {
        'articles':articles,
    }
    return render(request, 'articles.html', context)

def add_comment(request,id):
    article = get_object_or_404(Article, id=id)

    if request.method == 'POST':
        comment_author = request.user
        comment_content = request.POST.get('comment_content')

        new_comment = Comment(comment_author=comment_author, comment_content=comment_content)
        new_comment.article = article
        new_comment.save()
        return redirect(reverse('article:detail', kwargs={'id':id}))

user/views.py
from django.shortcuts import render,redirect
from .forms import RegisterForm,LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages
# Create your views here.

def register_user(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        
        new_user = User(username=username)
        new_user.set_password(password)
        new_user.save()

        login(request, new_user)
        messages.success(request, "Registered successfully!")
        return redirect('index')

    context = {
        'form':form,
    }
    return render(request, 'register.html',context)

def login_user(request):
    form = LoginForm(request.POST or None)
    context = {
        'form':form,
    }

    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')

        user = authenticate(username=username, password=password)
        if user is None:
            messages.error(request, 'Username or Password is wrong!')
            return render(request, 'login.html', context)

        messages.success(request, 'Logged in successfully!')
        login(request, user)
        return redirect('index')

    return render(request, 'login.html',context)

def logout_user(request):
    logout(request)
    messages.success(request, 'Logged out successfully!')
    return redirect('index')

templates/about.html
{% extends 'layout.html' %}

{% block body %}

<div class="jumbotron text-center">

<h3>About</h3>
 
</div>

{% endblock body %}

templates/add_article.html
{% extends 'layout.html' %}

{% block body %}

{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3> Create Article</h3><hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}<br>
            <button type="submit" class = "btn btn-info">Create</button>

        </form>
    </div>
</div>


{% endblock body %}

templates/articles.html
{% extends 'layout.html' %}

{% block body %}

<div class="row">
    <div class="col-md-2 offset-md-2">
        <h1>Articles</h1>
        <hr>
    </div>
    <form class="form-inline">
        {% csrf_token %}    
        <div class="form-group mx-sm-3 mb-2">
            <input type="text" class="form-control" name="keyword" placeholder="Search...">
        </div>
        <button type="submit" class="btn btn-primary mb-2">Search</button>
    </form>
</div>

{% if articles %}
    {% for article in articles %}
        <div class="row">
            <div class="col-md-14 offset-md-2">
                <!-- Post Content Column -->
                <div class="col-lg-8">
                    <!-- Title -->
                    <a href="{% url 'article:detail' article.id %}"><h3 class="mt-4">{{article.title}}</h3></a>
                    <!-- Author -->
                    <p class="lead">
                        by
                        {{article.author.username}}
                    </p>

                    <hr>

                    <!-- Date/Time -->
                    <p>Posted on {{article.created_date|date:"F d Y"}}<p>
                    <hr>
                    {% if article.article_image %}
                        <!-- Preview Image -->
                        <a href="{% url 'article:detail' article.id %}">
                            <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
                        </a>
                    {% endif %}

                    <hr>
                    <!-- Post Content -->
                    <p class="lead">
                    {{article.content|safe|truncatewords:20}}        
                    <a href="{% url 'article:detail' article.id %}">Read more</a>
                    </p>
                    <hr>
                    <hr>

                </div>
            </div>
        </div>


    {% endfor %}

{% else %}        
<div class="row">
    <div class="col-md-6 offset-md-2">
        <div class="alert alert-danger">
            There is no article to shown
        </div>
    </div>
</div>
{% endif %}
{% endblock body %}

templates/dashboard.html
{% extends 'layout.html' %}

{% block body %}

    <h3>Dashboard</h3>
    <hr>
    <a class="btn btn-info" href="/article/add_article">Add Article</a>
    <hr>
    {% if articles %}
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Author</th>
                    <th scope="col">Published date</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for article in articles%}
                    <tr>
                    <th scope="row">{{article.id}}</th>
                        <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
                        <td>{{article.author.username}}</td>
                        <td>{{article.created_date}}</td>
                        <td>
                        <a href="{% url 'article:update' article.id %}" class="btn btn-warning">Update</a>
                        <a href="{% url 'article:delete' article.id %}" class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-warning">
            You have no article yet..
        </div>
    {% endif %}

    
{% endblock body %}

templates/detail.html
{% extends 'layout.html' %}

{% block body %}
<div class="row">
  <!-- Post Content Column -->
  <div class="col-lg-8">
    <!-- Title -->
    <h1 class="mt-4">{{article.title}}</h1>
      <!-- Author -->
      <p class="lead">
        by
        {{article.author.username}}
      </p>

    <hr>

    <!-- Date/Time -->
    <p>Posted on {{article.created_date}}<p>
    <hr>
      {% if article.article_image %}
        <!-- Preview Image -->
        <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
      {% endif %}

    <hr>
    <!-- Post Content -->
    <p class="lead">
      {{article.content|safe}}        
    </p>

    <hr>

    {% if request.user.is_authenticated %}
      <!-- Comments Form -->
      <div class="card my-4">
        <h5 class="card-header">Leave a Comment:</h5>
          <div class="card-body">
            <form action ="{% url 'article:comment' article.id %}" method="POST">
            {% csrf_token %}
              <div class="form-group">
                {% comment %} <input type="text" class="form-control" name="keyword" placeholder="Comment Author">
                <hr> {% endcomment %}
                <textarea name="comment_content" class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Comment</button>
            </form>
          </div>
      </div>

    {% endif %}
    
    {% if comments %}
    {% for comment in comments %}
      <hr>
      <!-- Single Comment -->
      <div class="media mb-4">
        <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
        <div class="media-body">
          <h5 class="mt-0">{{comment.comment_author}}</h5>
            {{comment.comment_content}}
            <br><small>{{comment.comment_date|date:"F d Y"}}</small>
        </div>
      </div>
      <hr>
    {% endfor %}
    {% else %}
      <div class="alert alert-warning">
        There is no comment yet..
      </div>
    {% endif %}
  </div>
</div>
{% endblock body %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'index' %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'article:articles' %}">Articles</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Contact</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">

      {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'article:dashboard' %}">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
        </li>
        <li class="nav-item">
          <small class="nav-link disabled">{{request.user.username}}</small>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:login' %}">Login</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>

templates/index.html
{% extends 'layout.html' %}

{% block body %}

<div class="jumbotron text-center">

<h3>Homepage</h3>
 
</div>
{% endblock body %}

templates/layout.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %} ">

    <title>Djangolog</title>
  </head>
  <body>
        {% include "includes/navbar.html" %}
        <br>
        <div class = "container">
          {% if messages %}
              {% for message in messages %}
                <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
              {% endfor %}
          {% endif %}

            {% block body %}
            {% endblock body %}
        </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
  </body>
</html>

templates/login.html
{% extends 'layout.html' %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3> Login page</h3><hr>
        <form method = "post">
            {% csrf_token %}
            {{form|crispy}}<br>
            <button type="submit" class = "btn btn-info">Login</button>

        </form>
    </div>
</div>

{% endblock body %}

templates/logout.html
{% extends 'layout.html' %}

{% block body %}

<h3> Logout page</h3>


{% endblock body %}

templates/register.html
{% extends 'layout.html' %}

{% block body %}

{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3> Register page</h3><hr>
        <form method = "post">
            {% csrf_token %}
            {{form|crispy}}<br>
            <button type="submit" class = "btn btn-info">Register</button>

        </form>
    </div>
</div>


{% endblock body %}

templates/update.html
{% extends 'layout.html' %}

{% block body %}

{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3> Update Article</h3><hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}<br>
            <button type="submit" class = "btn btn-info">Update</button>

        </form>
    </div>
</div>


{% endblock body %}